---
title: "R Notebook"
output:
  html_document:
    df_print: paged
---


```{r}
library(tidyverse)
library(magrittr)
library(scales)
library(readxl)
library(pracma)
```

```{r}
load(file.path("Lottodata","lotto_aut.RData"))
```
```{r}
lotto_aut %>% names()
```

```{r}
lotto_aut %>% nrow()
```

Unser Datenbestand deckt `r lotto_aut %>% nrow()` Runden ab.


```{r}
lotto_aut %>%
  select(Rtot,Datum,Tipps,Wochentag) %>%
  ggplot(aes(x=Rtot,y=Tipps,color=Wochentag)) +
  geom_point() +
  facet_grid(Wochentag ~ .)
```


```{r}
lotto_aut %>%
  filter(JackpotDavor==0) %>%
  filter(Tipps <=30000000) %>%
  select(Rtot,Datum,Tipps,Wochentag) %>%
  ggplot(aes(x=Rtot,y=Tipps,color=Wochentag)) +
  geom_point(size=0.01) +
  geom_smooth() +
  facet_grid(Wochentag ~ .)
```

```{r}
probs_xl <- 
  read_excel(file.path("Lottodata",
                       "Probs_EN.xlsx")) %>%
  mutate(probs=choose(6,gruen)*choose(1,gelb)*
           choose(38,rot)/choose(45,6)) %>%
  select(Rang_Nr,Rang,probs)
probs_xl
```
```{r}
lotto_aut %>%
  select(Tipps,Wochentag,ProWoche,JackpotDavor,
         starts_with("Anzahl")) %>%
  mutate(TippsNeu=ifelse(!is.na(AnzahlZZ),Tipps,0)) ->
  probs_work
```

```{r}
probs_work %>%
  select(starts_with("Anzahl")) %>%
  gather(Rang,Anzahl) %>%
  group_by(Rang) %>%
  summarise(Anzahl=sum(Anzahl,na.rm=TRUE)) -> probs_rang
probs_rang
```
```{r}
probs_work %>%
  select(Tipps,TippsNeu) %>%
  summarise(Tipps=sum(Tipps),TippsNeu=sum(TippsNeu)) -> TippZahl

TippZahl
```
```{r}
Tipps_alt_neu <- function(Rang){
  ifelse(Rang %in% c("Anzahl3M","Anzahl4M","AnzahlZZ"), 
     TippZahl[[1,2]],TippZahl[[1,1]])
}
```

```{r}
probs_rang %>%
  mutate(Tipps=Tipps_alt_neu(Rang)) %>% 
  mutate(prob_emp=Anzahl/Tipps) %>% 
  mutate(Rang=str_sub(Rang,7)) -> probs

```
```{r}
probs
```
```{r}
left_join(probs,probs_xl)
```
```{r}
lotto_aut %>%
  select(JackpotDavor,Tipps,Anzahl6) %>%
  group_by(JackpotDavor) %>%
  summarise(Tipps=sum(Tipps),
            Sechser=sum(Anzahl6),Runden=n()) %>%
  mutate(TippsProRunde=Tipps/Runden)
  
```

