---
title: "Vorbereitung Wahlen"
output: html_notebook
---

```{r}
library(tidyverse)
library(magrittr)
library(scales)
library(readxl)
library(pracma)

library(cartogram)
library(sf)
library(patchwork)
```

# BPW Ergebnisse


```{r}
theme_map <- function(...) {
  theme_minimal() +
  theme(
#    text = element_text(family = "Ubuntu Regular", color = "#22211d"),
    axis.line = element_blank(),
    axis.text.x = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    # panel.grid.minor = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.major = element_line(color = "#ebebe5", size = 0.2),
    panel.grid.minor = element_blank(),
    plot.background = element_rect(fill = "#f5f5f2", color = NA), 
    panel.background = element_rect(fill = "#f5f5f2", color = NA), 
    legend.background = element_rect(fill = "#f5f5f2", color = NA),
    panel.border = element_blank(),
    ...
  )
}
```

```{r}
bpw2w_raw <-
  read_excel(file.path("Wahlen", "Endgueltiges_Gesamtergebnis_BPW16_2WG_WH.xlsx"),
             skip = 1)  %>% select(-8, -10)
names(bpw2w_raw) <-
  c("GKZ", "name", "wb", "abg", "ung", "glt", "Hofer", "VdB")
bpw2_raw <-
  read_excel(file.path("Wahlen", "Endgueltiges_Gesamtergebnis_BPW16_2WG.xlsx"),
             skip = 1)  %>% select(-8, -10)
names(bpw2_raw) <-
  c("GKZ", "name", "wb", "abg", "ung", "glt", "Hofer", "VdB")
bpw1_raw <-
  read_excel(file.path("Wahlen", "Endgueltiges_Gesamtergebnis_BPW16_1WG.xlsx"),
             skip = 1)  %>% select(-8, -10, -12, -14, -16, -18)
names(bpw1_raw) <-
  c(
    "GKZ", "name", "wb", "abg", "ung", "glt",
    "Griss", "Hofer", "Hundsdorfer", "Khol", "Lugner","VdB"
    )
```


NRW  Ergebnisse

```{r}
nrw13_raw <-
  read_excel(file.path("Wahlen", "NRW13_endgueltiges_Gesamtergebnis.xlsx"),
             skip = 1)  %>% select(1:3,5:7,seq(8,20,2))  
names(nrw13_raw) <-
  c(
    "GKZ", "name", "wb", "abg", "ung", "glt",
    "SPÖ","ÖVP","FPÖ","BZÖ","GRÜNE","FRANK","NEOS")

nrw17_raw <-
  read_excel(file.path("Wahlen", "NRW17_endgueltiges_Gesamtergebnis.xlsx"),
             skip = 1)  %>% select(1:7,seq(9,17,2))  

names(nrw17_raw) <-
  c(
    "GKZ", "name", "wb", "abg", "ung", "glt",
    "SPÖ","ÖVP","FPÖ","GRÜNE","NEOS","PILZ")
```


```{r}
load(file.path("Wahlen","nrw13_gem_adjusted.RData")) 
nrw13_gem_adjusted %<>% select(GKZ:NEOS)
names(nrw13_gem_adjusted) <-
  c(
    "GKZ", "wb", "abg", "ung", "glt",
    "SPÖ","ÖVP","FPÖ","BZÖ","GRÜNE","FRANK","NEOS")
```

# Filterfunktionen


```{r}
is_gemeinde <- function(GKZ){
  str_sub(GKZ,2) %>%
  str_detect(paste0("(",paste0(LETTERS,collapse="|"),")")) -> l1
  ifelse(!l1,
     as.numeric(str_sub(GKZ,2)),
     NA) -> num
  ifelse(is.na(num),
         FALSE,
         mod(num,100) != 0 & mod(num,100) != 99) 
}

is_bezirk <- function(GKZ){
  str_sub(GKZ,2) %>%
  str_detect(paste0("(",paste0(LETTERS,collapse="|"),")")) -> l1
  ifelse(!l1,
     as.numeric(str_sub(GKZ,2)),
     NA) -> num
  ifelse(is.na(num),
         FALSE,
         mod(num,100) == 0 & mod(floor(num/100),100) != 0) 
}

is_bundesland <- function(GKZ){
  str_sub(GKZ,2) %>%
  str_detect(paste0("(",paste0(LETTERS,collapse="|"),")")) -> l1
  ifelse(!l1,
     as.numeric(str_sub(GKZ,2)),
     NA) -> num
  ifelse(is.na(num),
         FALSE,
         mod(num,10000) == 0 ) 
}
```

# Landkarten



```{r}
bezmap <- read_sf(file.path("Wahlen","Landkarten","bezirke_95_geo.json"))
autborder <- read_sf(file.path("Wahlen","Landkarten","nur_oesterreich.json"))
blborder <-  read_sf(file.path("Wahlen","Landkarten","laender_95_geo.json"))
bezmap_mit_wienbez <- read_sf(file.path("Wahlen","Landkarten","Bezirke mit Wien.geojson"))
gemeinden <- read_sf(file.path("Wahlen","Landkarten","gemeinden_mit_wiener_bezirken.json"))
```


```{r}
bpw2w_raw %>%
  filter(is_bezirk(GKZ)) %>%
  mutate(iso=floor(as.numeric(str_sub(GKZ,2))/100)) %>% 
  mutate(vdb=VdB/glt,hofer=Hofer/glt) %>%
  select(iso,wb,vdb,hofer) -> vdb_hofer_2w
```

```{r}
bezmap_mit_wienbez %>% 
  left_join(vdb_hofer_2w) %>%
  ggplot() +
  geom_sf(aes(fill=vdb)) +
  scale_fill_gradient2(high=muted("green"),midpoint=0.5) +
  theme(axis.text=element_blank(),
        axis.ticks=element_blank(),
        plot.background = element_rect(fill="white"),
        panel.background = element_rect(fill="white")) -> pv
pv
```


```{r}
bezmap_mit_wienbez %>% 
  left_join(vdb_hofer_2w) %>%
  ggplot() +
  geom_sf(aes(fill=hofer)) +
  scale_fill_gradient2(high=muted("blue"),midpoint=0.5) +
  theme(axis.text=element_blank(),
        axis.ticks=element_blank(),
        plot.background = element_rect(fill="white"),
        panel.background = element_rect(fill="white")) ->
  ph
ph
```
```{r}
pv + ph
```


```{r}
bezmap_mit_wienbez %>% 
  left_join(vdb_hofer_2w) %>%
  ggplot() +
  geom_sf(aes(fill=vdb)) +
  scale_fill_gradient2(high=muted("green"),low=muted("blue"),midpoint=0.5) +
  theme(axis.text=element_blank(),
        axis.ticks=element_blank(),
        plot.background = element_rect(fill="white"),
        panel.background = element_rect(fill="white")) -> pv
pv
```


```{r, warning=FALSE, message=FALSE}
bezmap_mit_wienbez %>%
  left_join(vdb_hofer_2w) %>%
  as_Spatial() %>% cartogram_cont(weight="wb",20) %>% st_as_sf() -> bezwiencarto
```

```{r}
bezwiencarto %>% 
  left_join(vdb_hofer_2w) %>%
  ggplot() +
  geom_sf(aes(fill=vdb)) +
  scale_fill_gradient2(high=muted("green"),midpoint=0.5) +
  theme(axis.text=element_blank(),
        axis.ticks=element_blank(),
        plot.background = element_rect(fill="white"),
        panel.background = element_rect(fill="white")) -> pv1
pv1
```

```{r}
bezwiencarto %>% 
  left_join(vdb_hofer_2w) %>%
  ggplot() +
  geom_sf(aes(fill=hofer)) +
  scale_fill_gradient2(high=muted("blue"),midpoint=0.5) +
  theme(axis.text=element_blank(),
        axis.ticks=element_blank(),
        plot.background = element_rect(fill="white"),
        panel.background = element_rect(fill="white")) ->
  ph1
ph1
```


```{r}
pv1 + ph1 
```


```{r}
pv1 + ph1 + plot_layout(ncol=1) 
```
```{r}
bezwiencarto %>% 
  left_join(vdb_hofer_2w) %>%
  ggplot() +
  geom_sf(aes(fill=vdb)) +
  scale_fill_gradient2(high=muted("green"),low=muted("blue"),midpoint=0.5) +
  theme(axis.text=element_blank(),
        axis.ticks=element_blank(),
        plot.background = element_rect(fill="white"),
        panel.background = element_rect(fill="white")) -> pv
pv
```

```{r}
my_df <- data_frame(
  name = c("Bad Vöslau", "Salzburg"),
  province = c("Niederösterreich", "Salzburg"),
  y = c(47.96694, 47.8),
  x = c(16.21444, 13.03333)
)


bezmap_mit_wienbez %>%
  ggplot() +
  geom_sf(fill = "white") +
  geom_point(aes(x, y),
             size = 2,
             data = my_df,
             color = "red") +
  geom_line(aes(x, y),data=my_df)
```


```{r}
nrw17_raw %>%
  filter(is_gemeinde(GKZ)) %>%
  mutate_at(vars(SPÖ:PILZ),funs(./wb)) %>%
  select(GKZ,wb,SPÖ:PILZ) %>% 
  mutate(iso=as.numeric(str_sub(GKZ,2)))  -> 
  nrw17_gem
```


```{r}
nrw13_gem_adjusted %>%
  select(GKZ,wb,SPÖ:NEOS) %>%
  mutate_at(vars(SPÖ:NEOS),funs(./wb)) %>%
  mutate(iso=as.numeric(str_sub(GKZ,2))) -> 
  nrw13_gem
```


```{r}
nrw1317_gem <- 
  left_join( 
    (nrw13_gem %>%
       mutate(iso=GKZ)),
    nrw17_gem,by="iso")
```

```{r, warning=FALSE, message=FALSE}
gemeinden %>%
  left_join(nrw17_gem) %>%
  as_Spatial() %>% cartogram_cont(weight="wb",3) %>% st_as_sf() -> 
  gemeinden_carto
```

```{r}
signed_percent <- function(x,digits=1,width=4){
  prefix <- ifelse(x>0,"+","")
  prefix <- ifelse(x==0,"±",prefix)
  str_pad(paste0(prefix,format(100*x,digits),"%"),
          width=width,pad=" ")
}
  
signed_percent(0.12,width=5)
```


```{r}
gemeinden %>% 
  left_join(nrw1317_gem) %>%
  mutate(ÖVP=ÖVP.y-ÖVP.x) %>%
  ggplot() +
  geom_sf(aes(fill=ÖVP),lwd=0) +
  geom_sf(data=autborder,fill=NA) +
  scale_fill_gradient2(low=muted("red"),
                       high="turquoise4",mid="white",midpoint=0,
                       labels=signed_percent,
                       breaks=seq(-0.2,0.2,0.05)) +
  theme_map() 
```

```{r}
gemeinden %>% 
  left_join(nrw1317_gem) %>%
  mutate(SPÖ=SPÖ.y-SPÖ.x) %>%
  ggplot() +
  geom_sf(aes(fill=SPÖ),lwd=0) +
  geom_sf(data=autborder,fill=NA) +
  scale_fill_gradient2(low="blue",
                       high="red",mid="white",midpoint=0,
                       labels=signed_percent,
                       breaks=seq(-0.25,0.2,0.05)) +
#                       breaks=seq(-0.3,0.3,0.05)) +
 theme_map() 
```
```{r}
gemeinden %>% 
  left_join(nrw1317_gem) %>%
  mutate(FPÖ=FPÖ.y-FPÖ.x) %>%
  ggplot() +
  geom_sf(aes(fill=FPÖ),lwd=0) +
  geom_sf(data=autborder,fill=NA) +
  scale_fill_gradient2(low="red",
                       high="blue",mid="white",midpoint=0,
                       labels=signed_percent,
                       breaks=seq(-0.1,0.2,0.05)) +
  theme_map() 
```
```{r}
gemeinden %>% 
  left_join(nrw1317_gem) %>%
  mutate(GRÜNE=GRÜNE.y-GRÜNE.x) %>%
  ggplot() +
  geom_sf(aes(fill=GRÜNE),lwd=0) +
  geom_sf(data=autborder,fill=NA) +
  scale_fill_gradient2(low="red",
                       high="green",mid="white",midpoint=0,
                       labels=signed_percent,
                       breaks=seq(-0.1,0.1,0.05)) +
  theme_map() 
```

```{r}
gemeinden %>% 
  left_join(nrw1317_gem) %>%
  mutate(NEOS=NEOS.y-NEOS.x) %>%
  ggplot() +
  geom_sf(aes(fill=NEOS),lwd=0) +
    geom_sf(data=autborder,fill=NA) +
  scale_fill_gradient2(low="blue",
                       high=muted("pink"),mid="white",midpoint=0,
                       labels=signed_percent) +
  theme_map() 
```

```{}
gemeinden_carto %>% 
  left_join(nrw1317_gem) %>%
  mutate(ÖVP=ÖVP.y-ÖVP.x) %>%
  ggplot() +
  geom_sf(aes(fill=ÖVP)) +
  scale_fill_gradient2(low=muted("red"),
                       high="turquoise4",mid="white",midpoint=0) +
  theme_map() 
```

